<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NikkeLocalLab.PostgreSql.IntegrationTests/NikkeLocalLab.PostgreSql.IntegrationTests.csproj" />
    <ProjectReference Include="../../src/NikkeLocalLab.Admin.Api/NikkeLocalLab.Admin.Api.csproj" />
  </ItemGroup>
</Project>
