<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Formats.Nrbf">
      <HintPath>$(MSBuildSDKsPath)\..\System.Formats.Nrbf.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
