<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Compile Include="..\..\scripts\Nll.PhaseDJob.cs" Link="OfflinePipeline\ExecutionJob.cs" />
    <ProjectReference Include="..\NikkeLocalLab.Application.PrivateServer\NikkeLocalLab.Application.PrivateServer.csproj" />
    <ProjectReference Include="..\NikkeLocalLab.Application.ProfileManagement\NikkeLocalLab.Application.ProfileManagement.csproj" />
    <ProjectReference Include="..\NikkeLocalLab.Configuration\NikkeLocalLab.Configuration.csproj" />
    <ProjectReference Include="..\NikkeLocalLab.Domain.PrivateServer\NikkeLocalLab.Domain.PrivateServer.csproj" />
    <ProjectReference Include="..\NikkeLocalLab.Identity\NikkeLocalLab.Identity.csproj" />
    <ProjectReference Include="..\NikkeLocalLab.Persistence.PostgreSql\NikkeLocalLab.Persistence.PostgreSql.csproj" />
  </ItemGroup>
</Project>
